### PR TITLE
Fix to FortranWrapper.h that enables SerialBox to compile with Fortran features on MacOS

### PR DESCRIPTION
**Pull request by gmao-ckung**
Compiling the current master branch on MacOS Catalina results in the following undefined symbol errors

```
Undefined symbols for architecture x86_64: 
  "_serialboxFortranSavepointAddMetainfoInt64", referenced from: 
      ___m_serialize_MOD_fs_add_savepoint_metainfo_l in m_serialize.f90.o 
  "_serialboxFortranSavepointGetMetainfoInt64", referenced from: 
      ___m_serialize_MOD_fs_get_savepoint_metainfo_l in m_serialize.f90.o 
  "_serialboxFortranSerializerAddFieldMetainfoInt64", referenced from: 
      ___m_serialize_MOD_fs_add_field_metainfo_l in m_serialize.f90.o 
  "_serialboxFortranSerializerAddMetainfoInt64", referenced from: 
      ___m_serialize_MOD_fs_add_serializer_metainfo_l in m_serialize.f90.o 
  "_serialboxFortranSerializerGetFieldMetainfoInt64", referenced from: 
      ___m_serialize_MOD_fs_get_field_metainfo_l in m_serialize.f90.o 
  "_serialboxFortranSerializerGetMetainfoInt64", referenced from: 
      ___m_serialize_MOD_fs_get_serializer_metainfo_l in m_serialize.f90.o 
```
The fix is to change the `long` and `long*` parameter types for the `Int64` routines in `FortranWrapper.h` to `int64_t` and `int64_t*` respectively.

This was tested using MacOS Catalina v 10.15.7 and built using MacOS clang-based C and C++ compilers and gfortran v 11.1.0 installed via Homebrew.

### CODE REVIEW

**Comment by gmao-ckung** [comment]
Yes

**Comment by gmao-ckung** [comment]
Yes verify the patch

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
Thanks, for the contribution. Please merge with the updated master to reflect the fixes in CI.

**Comment by havogt** [comment]
Additionally, please update the `AUTHORS` file with your name and affiliation.

**Comment by havogt** [comment]
And in case your are motivated, a PR to extending the GitHub action tests to MacOS is very welcome, see #246.

**Comment by havogt** [comment]
Hi @gmao-ckung,
for contributions to the GridTools framework, which contains Serialbox, I need to ask you to sign the [contributor assignment agreement](https://github.com/GridTools/CAA/blob/main/GridToolsCAA.pdf). (I thought you are employed at Vulcan, which would have been covered already.) Please send the signed document to vogt@cscs.ch. Alternatively, for this particular, obvious contribution, I can merge directly, if you confirm that such a contribution is not copyrightable and you remove yourself again from the `AUTHORS` list. Sorry, for the confusion.

**Comment by gmao-ckung** [comment]
Hi @havogt,

I apologize for the confusion about my affiliation.  Given that this fix is relatively small, I think it’ll be easiest if I take my name off the “AUTHORS” list.  I’ll resubmit a version with my name off the list.

**Comment by havogt** [comment]
Please give Andrea his `n` back. ;)

**Comment by gmao-ckung** [comment]
Good catch!

**Comment by havogt** [comment]
Thanks again for the fix!

**Pull request merged**
