### PR TITLE
Rename arolla to tsa

### PR DESCRIPTION
**Pull request by yboetz**
We changed all paths and option files from arolla to tsa. With these changes serialbox does not install on tsa anymore, since the build script checks only for host arolla and then fails to load the correct env file.

I also disabled cray compiler on tsa, since we don't support it anymore.

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
@yboetz I think for all you cases you should actually not use this script to install, but use the package builder from the buildenv. Are you aware of this?

**Comment by havogt** [comment]
launch jenkins

**Comment by yboetz** [comment]
> @yboetz I think for all you cases you should actually not use this script to install, but use the package builder from the buildenv. Are you aware of this?

I didn't know this. I only saw that the serialbox2 plan is failing, and that one is using this script. But @lxavier now told me that serialbox2_release is the plan we actually use and that one is using the package builder.

**Pull request merged**
